import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { AI } from '../lib/chat/actions';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <AI>
          <main className='container mx-auto w-full max-w-6xl h-full min-h-screen p-12 bg-white'>
            {children}
          </main>
        </AI>
      </body>
    </html>
  );
}
